Repository Team-Walkie/Walkie, pull requests merged in 2023-10, with the labels that each got.

#46 러닝 시작, 종료 api 연결
  app/src/main/java/com/whyranoid/walkie/KoinModules.kt
  data/src/main/java/com/whyranoid/data/API.kt
  data/src/main/java/com/whyranoid/data/AppDataBase.kt
  data/src/main/java/com/whyranoid/data/datasource/running/RunningControlDataSourceImpl.kt
  data/src/main/java/com/whyranoid/data/datasource/running/RunningHistoryDao.kt
  data/src/main/java/com/whyranoid/data/datasource/running/RunningService.kt
  data/src/main/java/com/whyranoid/data/model/running/LikeTotalResponse.kt
  data/src/main/java/com/whyranoid/data/model/running/RunningFinishRequest.kt
  data/src/main/java/com/whyranoid/data/model/running/RunningHistoryEntity.kt
  data/src/main/java/com/whyranoid/data/model/running/RunningStartRequest.kt
  data/src/main/java/com/whyranoid/data/model/running/SendLikeRequest.kt
  data/src/main/java/com/whyranoid/data/repository/RunningHistoryRepositoryImpl.kt
  data/src/main/java/com/whyranoid/data/repository/RunningRepositoryImpl.kt
  domain/src/main/java/com/whyranoid/domain/datasource/RunningControlDataSource.kt
  domain/src/main/java/com/whyranoid/domain/repository/RunningRepository.kt
  domain/src/main/java/com/whyranoid/domain/usecase/running/RunningFinishUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/running/RunningStartUseCase.kt
  presentation/src/main/java/com/whyranoid/presentation/viewmodel/RunningViewModel.kt
Labels: enhancement

#47 운동 위치 포스팅 기록에 포함시켜서 업로드, 업로딩 프로그래스바 생성
  domain/src/main/java/com/whyranoid/domain/model/post/PostPreview.kt
  presentation/src/main/java/com/whyranoid/presentation/reusable/CircleProgressWithText.kt
  presentation/src/main/java/com/whyranoid/presentation/screens/mypage/MyPageScreen.kt
  presentation/src/main/java/com/whyranoid/presentation/screens/mypage/addpost/AddPostScreen.kt
  presentation/src/main/java/com/whyranoid/presentation/screens/mypage/addpost/PostingScreen.kt
  presentation/src/main/java/com/whyranoid/presentation/screens/mypage/tabs/PostPage.kt
  presentation/src/main/java/com/whyranoid/presentation/viewmodel/AddPostViewModel.kt
Labels: enhancement

#48 현재 달리는 팔로잉 유저 확인
  app/src/main/java/com/whyranoid/walkie/KoinModules.kt
  data/src/main/java/com/whyranoid/data/repository/RunningRepositoryImpl.kt
  domain/src/main/java/com/whyranoid/domain/repository/RunningRepository.kt
  domain/src/main/java/com/whyranoid/domain/usecase/running/GetRunningFollowerUseCase.kt
  domain/src/main/java/com/whyranoid/domain/usecase/running/SendLikeUseCase.kt
  presentation/src/main/java/com/whyranoid/presentation/component/community/RunningFollowerItem.kt
  presentation/src/main/java/com/whyranoid/presentation/component/running/RunningFollowerItemWithLikable.kt
  presentation/src/main/java/com/whyranoid/presentation/screens/running/RunningScreen.kt
  presentation/src/main/java/com/whyranoid/presentation/viewmodel/RunningViewModel.kt
Labels: enhancement

#49 권한 요청 및 gps, 네트워크 상태 관리 다이얼로그 추가
  app/build.gradle.kts
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/whyranoid/walkie/KoinModules.kt
  app/src/main/java/com/whyranoid/walkie/MainActivity.kt
  app/src/main/java/com/whyranoid/walkie/walkiedialog/AppManageDialog.kt
  app/src/main/java/com/whyranoid/walkie/walkiedialog/DialogContentProvider.kt
  app/src/main/java/com/whyranoid/walkie/walkiedialog/DialogState.kt
  app/src/main/java/com/whyranoid/walkie/walkiedialog/DialogViewModel.kt
  app/src/main/java/com/whyranoid/walkie/wlakiedialog/DialogState.kt
  build.gradle.kts
  domain/src/main/java/com/whyranoid/domain/usecase/broadcast/AddGpsListener.kt
  domain/src/main/java/com/whyranoid/domain/usecase/broadcast/AddNetworkListener.kt
  domain/src/main/java/com/whyranoid/domain/usecase/broadcast/GetGpsState.kt
  domain/src/main/java/com/whyranoid/domain/usecase/broadcast/GetNetworkState.kt
  domain/src/main/java/com/whyranoid/domain/usecase/broadcast/RemoveGpsListener.kt
  domain/src/main/java/com/whyranoid/domain/usecase/broadcast/RemoveNetworkListener.kt
  presentation/src/main/java/com/whyranoid/presentation/screens/AppScreen.kt
  presentation/src/main/java/com/whyranoid/presentation/screens/signin/SignInAgreeScreen.kt
  presentation/src/main/java/com/whyranoid/presentation/screens/signin/SignInUserNameScreen.kt
  presentation/src/main/java/com/whyranoid/presentation/screens/splash/SplashScreen.kt
  presentation/src/main/java/com/whyranoid/presentation/util/extensions.kt
Labels: enhancement, Distribution

#51 Pager 의존성 문제 해결
  presentation/build.gradle.kts
  presentation/src/main/java/com/whyranoid/presentation/screens/challenge/ChallengeMainScreen.kt
  presentation/src/main/java/com/whyranoid/presentation/screens/mypage/MyPageScreen.kt
Labels: ASAP
